services:
  mysql:
    image: mysql:8.0
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    build:
      context: ${DOCKER_FILE_FOLDER}
      dockerfile: Dockerfile-mysql
    volumes:
      - "${DB_DATA_PATH}:/var/lib/mysql"
    ports:
      - 3344:3306
    container_name: mysql

  redis-standalone:
    image: redis:6.0.9
    ports:
      - 6379:6379
    container_name: redis-standalone
